version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 4000:4000

  web:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    volumes:
      - ./web:/web
    ports:
      - 3000:3000
